<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- Packability-->
  <PropertyGroup>
    <IsPackable>True</IsPackable>
  </PropertyGroup>

  <!-- Package Information-->
  <PropertyGroup>
    <Title>Defra Livestock API SDK - Strategies</Title>
    <Description>Fluent strategy builders</Description>
    <RepositoryUrl>https://github.com/DEFRA/lis-sdk-nuget-api-strategies</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- Local Version Information-->
  <PropertyGroup>
    <Version>0.6.0-prerelease.1</Version>
  </PropertyGroup>

  <!-- Packages-->
  <ItemGroup>
    <PackageReference Include="Defra.Livestock.Sdk.Api.Strategies.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Defra.Livestock.Sdk.Api.Strategies.Tests" />
  </ItemGroup>
</Project>
